### ISSUE TITLE
Fehlende Unterstützung für pizza.de-Deals

### ISSUE THREAD

**Issue by JumpmanJunior** [breunigs/hipsterpizza#30]
Viele Lieferdienste bieten hier pizza.de-Deals an. Wenn man mit einem pizza.de-Account bestellt, bekommt man bis zu 40% Rabatt. Diese Rabatte werden aber von HipsterPizza nicht unterstützt, da auch der pizza.de-Login nicht unterstützt wird. Wäre gut, wenn man das irgendwie einbauen könnte, da hier keiner bereit ist den normalen Preis zu zahlen. Zumal die Lieferdienste mit dem Rabatt kalkulieren und der Normalpreis entsprechend überteuert ist.

**Comment by breunigs** [comment]
Duplicate of #11
