### ISSUE TITLE
Site Down

### ISSUE THREAD

**Issue by xremix** [breunigs/hipsterpizza#34]
it seems the Site for Hipster Pizza is down.

**Comment by xremix** [comment]
![bildschirmfoto 2016-01-07 um 11 28 32](https://cloud.githubusercontent.com/assets/9824294/12168338/cf8019be-b531-11e5-81f5-d4679c6d66a3.png)

**Comment by breunigs** [comment]
I am aware. My server currently doesn't have enough resources to run all projects I need it for.

**Comment by breunigs** [comment]
It's up again. Enjoy.

**Comment by xremix** [comment]
cool thanks, I might try it on friday :+1:
